# --------------------------------------------- #
# Globals
# --------------------------------------------- #
INTERPRETER = python3

# File:main_test_txt2enc.py
# --------------------------------------------- #
SCRIPT_TXT_2_ENC = main_test_txt2enc.py
ARGS_TXT_2_ENC = --input-file ./input.txt --output-dest ./out.txt


# --------------------------------------------- #
# Tasks
# --------------------------------------------- #
test_huffman_enc_txt2enc:
	chmod u+x $(SCRIPT_TXT_2_ENC)
	$(INTERPRETER) $(SCRIPT_TXT_2_ENC) $(ARGS_TXT_2_ENC)
