# ======================== #
# Variables
# ======================== #

RUN_PROGRAM = run_program.sh


# ======================== #
# Targets
# ======================== #

run_program_eval_on_cameramen:
	chmod u+x $(RUN_PROGRAM)
	./$(RUN_PROGRAM)

