# ======================== #
# Variables
# ======================== #

RUN_PROGRAM = run_program.sh
RUN_TINY_EXAMPLE = run_tiny_example.sh
RUN_FULL_EXAMPLE = run_full_example.sh


# ======================== #
# Targets
# ======================== #

run_program:
	chmod u+x $(RUN_PROGRAM)
	$(RUN_PROGRAM)

run_full_example:
	chmod u+x $(RUN_FULL_EXAMPLE)
	./$(RUN_FULL_EXAMPLE)

run_tiny_example:
	chmod u+x $(RUN_TINY_EXAMPLE)
	./$(RUN_TINY_EXAMPLE)

