# ======================== #
# Variables
# ======================== #

RUN_PROGRAM = run_program.sh
RUN_PROGRAM_DYNAMIC_QUANT = run_program_dynamic_quant.sh
RUN_TINY_EXAMPLE = run_tiny_example.sh
RUN_FULL_EXAMPLE = run_full_example.sh


# ======================== #
# Targets
# ======================== #

run_program_train_on_cameramen:
	chmod u+x $(RUN_PROGRAM)
	./$(RUN_PROGRAM)

run_program_train_on_cameramen_dynamic_quant:
	chmod u+x $(RUN_PROGRAM_DYNAMIC_QUANT)
	./$(RUN_PROGRAM_DYNAMIC_QUANT)


run_full_example_train_on_cameramen:
	chmod u+x $(RUN_FULL_EXAMPLE)
	./$(RUN_FULL_EXAMPLE)

run_tiny_example_train_on_cameramen:
	chmod u+x $(RUN_TINY_EXAMPLE)
	./$(RUN_TINY_EXAMPLE)

