SCRIPT_GET_REMOTE_DATA = get_train_log-v001.sh
ARGS_GET_REMOTE_DATA = conf.txt

# =============================================== #
# Targets
# =============================================== #

get_train_log:
	chmod u+x $(SCRIPT_GET_REMOTE_DATA)
	./$(SCRIPT_GET_REMOTE_DATA) $(ARGS_GET_REMOTE_DATA)